import { useRef } from 'react'
import { X, Download, Share2, CheckCircle2, ExternalLink, Printer } from 'lucide-react'
import type { TrackedTransaction } from '@/store/transactions'
import type { TransactionType, TransactionMetadata } from '@/lib/transactions'
import { formatNumber } from '@/lib/utils'
import { getExplorerUrl, getNetworkDisplayName } from '@/lib/solana/config'

interface DisplayTransaction extends Omit<TrackedTransaction, 'type'> { type: TransactionType; metadata?: TransactionMetadata }
interface TransactionReceiptProps { transaction: DisplayTransaction | TrackedTransaction; onClose: () => void }

const getTypeName = (type: string) => ({ send: 'Transfer Out', receive: 'Transfer In', bet: 'Bet Placed', reward: 'Reward Claimed', stake: 'Tokens Staked', unstake: 'Tokens Unstaked', swap: 'Token Swap', transfer: 'Transfer' }[type] || 'Transaction')
const formatDate = (ts: number) => new Date(ts).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' })
const shortenAddress = (addr: string, chars = 8) => addr.length <= chars * 2 + 3 ? addr : `${addr.slice(0, chars)}...${addr.slice(-chars)}`

export function TransactionReceipt({ transaction, onClose }: TransactionReceiptProps) {
  const receiptRef = useRef<HTMLDivElement>(null)
  const isOutgoing = transaction.type === 'send' || transaction.type === 'stake'
  const networkName = getNetworkDisplayName()
  const metadata = 'metadata' in transaction ? transaction.metadata : undefined

  const handleShare = async () => {
    if (!transaction.signature) return
    const text = `Transaction Receipt\n\nType: ${getTypeName(transaction.type)}\n${metadata?.amount !== undefined ? `Amount: ${isOutgoing ? '-' : '+'}${formatNumber(metadata.amount)} ${metadata?.token || ''}\n` : ''}Status: Confirmed\nDate: ${formatDate(transaction.createdAt)}\n\nView: ${getExplorerUrl(transaction.signature, 'tx')}`
    if (navigator.share) try { await navigator.share({ title: 'Transaction Receipt', text }) } catch {}
    else await navigator.clipboard.writeText(text)
  }

  const handleDownload = () => {
    const content = `DOOMSDAY TRANSACTION RECEIPT\n============================\n\nType: ${getTypeName(transaction.type)}\n${metadata?.amount !== undefined ? `Amount: ${isOutgoing ? '-' : '+'}${formatNumber(metadata.amount)} ${metadata?.token || ''}\n` : ''}Status: ${transaction.status.toUpperCase()}\nDate: ${formatDate(transaction.createdAt)}\n\nDescription:\n${transaction.description}\n\n${transaction.signature ? `Signature:\n${transaction.signature}` : ''}\n\n${metadata?.recipient ? `To: ${metadata.recipient}\n` : ''}${metadata?.sender ? `From: ${metadata.sender}\n` : ''}${metadata?.eventTitle ? `Event: ${metadata.eventTitle}\n` : ''}${metadata?.fee !== undefined ? `Fee: ${(metadata.fee / 1e9).toFixed(6)} SOL\n` : ''}\nNetwork: ${networkName}\n${transaction.signature ? `Explorer: ${getExplorerUrl(transaction.signature, 'tx')}` : ''}\n\n============================\nGenerated by Doomsday App`
    const blob = new Blob([content], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `receipt-${transaction.id.slice(0, 8)}.txt`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4">
      <div className="bg-white w-full max-w-md rounded-2xl overflow-hidden">
        <div className="bg-[#1a1a1a] p-4 flex items-center justify-between print:hidden">
          <h2 className="text-[18px] font-bold text-white">Transaction Receipt</h2>
          <button onClick={onClose} className="p-2 hover:bg-[#333] rounded-full"><X size={20} className="text-white" /></button>
        </div>
        <div ref={receiptRef} className="p-6 bg-white text-black">
          <div className="text-center mb-6"><h1 className="text-[24px] font-bold">DOOMSDAY</h1><p className="text-[12px] text-gray-500 uppercase tracking-wider">Transaction Receipt</p></div>
          <div className="flex justify-center mb-6"><div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center"><CheckCircle2 size={40} className="text-green-600" /></div></div>
          {metadata?.amount !== undefined && <div className="text-center mb-6"><p className="text-[32px] font-bold" style={{ color: isOutgoing ? '#dc2626' : '#16a34a' }}>{isOutgoing ? '-' : '+'}{formatNumber(metadata.amount)}</p>{metadata.token && <p className="text-[14px] text-gray-500">{metadata.token}</p>}</div>}
          <div className="border-t border-b border-gray-200 py-4 space-y-3">
            <div className="flex justify-between"><span className="text-[13px] text-gray-500">Type</span><span className="text-[13px] font-medium">{getTypeName(transaction.type)}</span></div>
            <div className="flex justify-between"><span className="text-[13px] text-gray-500">Status</span><span className="text-[13px] font-medium text-green-600">Confirmed</span></div>
            <div className="flex justify-between"><span className="text-[13px] text-gray-500">Date</span><span className="text-[13px] font-medium">{formatDate(transaction.createdAt)}</span></div>
            {transaction.signature && <div className="flex justify-between"><span className="text-[13px] text-gray-500">Transaction ID</span><span className="text-[13px] font-mono">{shortenAddress(transaction.signature)}</span></div>}
            {metadata?.recipient && <div className="flex justify-between"><span className="text-[13px] text-gray-500">To</span><span className="text-[13px] font-mono">{shortenAddress(metadata.recipient, 6)}</span></div>}
            {metadata?.sender && <div className="flex justify-between"><span className="text-[13px] text-gray-500">From</span><span className="text-[13px] font-mono">{shortenAddress(metadata.sender, 6)}</span></div>}
            {metadata?.eventTitle && <div className="flex justify-between"><span className="text-[13px] text-gray-500">Event</span><span className="text-[13px] font-medium max-w-[180px] truncate">{metadata.eventTitle}</span></div>}
            {metadata?.fee !== undefined && <div className="flex justify-between"><span className="text-[13px] text-gray-500">Fee</span><span className="text-[13px] font-medium">{(metadata.fee / 1e9).toFixed(6)} SOL</span></div>}
            <div className="flex justify-between"><span className="text-[13px] text-gray-500">Network</span><span className="text-[13px] font-medium">{networkName}</span></div>
          </div>
          <div className="py-4 border-b border-gray-200"><p className="text-[12px] text-gray-500 mb-1">Description</p><p className="text-[13px]">{transaction.description}</p></div>
          <div className="pt-4 text-center"><p className="text-[11px] text-gray-400">Powered by Solana Blockchain</p>{transaction.signature && <a href={getExplorerUrl(transaction.signature, 'tx')} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-[11px] text-blue-600 hover:underline mt-1">Verify on Solana Explorer<ExternalLink size={10} /></a>}</div>
        </div>
        <div className="bg-gray-50 p-4 flex gap-2 print:hidden">
          <button onClick={handleDownload} className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl border border-gray-300 text-[14px] font-semibold text-gray-700 hover:bg-gray-100"><Download size={16} />Download</button>
          <button onClick={() => window.print()} className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl border border-gray-300 text-[14px] font-semibold text-gray-700 hover:bg-gray-100"><Printer size={16} />Print</button>
          <button onClick={handleShare} className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl bg-black text-white text-[14px] font-semibold hover:bg-gray-800"><Share2 size={16} />Share</button>
        </div>
      </div>
    </div>
  )
}
